#!/bin/bash

if [[ -z "$1" ]]; then
  echo "Please provide a valid hostname for the cert"
  exit 1
fi

if [[ -z "$2" ]]; then
  service_name=service
else
  service_name="$2"
fi

grid-cert-request -host "$1" -dir /myproxy-gateway/hostcerts -service "${service_name}" -prefix "${service_name}" -nopw
echo "globus" | grid-ca-sign -days 3650 -in "${service_name}cert_request.pem" -out "${service_name}cert.pem"
openssl rsa -in "${service_name}key.pem" -outform PEM -out "new-${service_name}key.pem"

echo "New host cert for ${service_name}/$1 is: "
cat "${service_name}cert.pem"
echo ""
echo "New host key for ${service_name}/$1 is: "
cat "new-${service_name}key.pem"
echo ""
